name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/exam-tracker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/exam-tracker:${{ github.sha }}

      - name: Deploy to EC2 (ubuntu login, root execution)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/exam-tracker:latest

            sudo docker stop exam-tracker || true
            sudo docker rm exam-tracker || true

            sudo docker run -d \
              --name exam-tracker \
              --restart always \
              -p 8000:8000 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e CLIENT_ID='${{ secrets.CLIENT_ID }}' \
              -e CLIENT_SECRET='${{ secrets.CLIENT_SECRET }}' \
              -e SPRING_GOOGLE_OAUTH_REDIRECT_URI='${{ secrets.SPRING_GOOGLE_OAUTH_REDIRECT_URI }}' \
              -e SPRING_GOOGLE_OAUTH_RESPONSE_COOKIE='${{ secrets.SPRING_GOOGLE_OAUTH_RESPONSE_COOKIE }}' \
              -e DB_URL='${{ secrets.DB_URL }}' \
              -e MYSQL_USERNAME='${{ secrets.MYSQL_USERNAME }}' \
              -e MYSQL_PASSWORD='${{ secrets.MYSQL_PASSWORD }}' \
              -e SPRING_AUTH_ACCESS_TOKEN_COOKIE_NAME='${{ secrets.SPRING_AUTH_ACCESS_TOKEN_COOKIE_NAME }}' \
              -e SPRING_DOMAIN_NAME='${{ secrets.SPRING_DOMAIN_NAME }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -e PORT='${{ secrets.PORT }}' \
              ${{ secrets.DOCKERHUB_USERNAME }}/exam-tracker:latest
